package deepalert

// Task is invoke argument of inspectors
type Task struct {
	ReportID  ReportID   `json:"report_id"`
	Attribute *Attribute `json:"attribute"`
}

// TaskResult is generated by Inspector and can have both of contents and
// new atributes because of efficiecy.
type TaskResult struct {
	Contents      []ReportContent
	NewAttributes []*Attribute
}
