name: test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.25.x', '1.26.x']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: test
        run: go test ./...
        env:
          GO111MODULE: on
